# Generated by Django 3.1.2 on 2020-10-23 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата с'),
        ),
    ]
