# Generated by Django 3.1.2 on 2020-10-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_price', '0002_auto_20201024_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_finish',
            field=models.DateField(blank=True, default=9956, verbose_name='Дата по'),
        ),
    ]
