# Generated by Django 3.1.2 on 2020-10-25 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_price', '0003_auto_20201024_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date_start', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата с')),
                ('date_finish', models.DateField(blank=True, default='9999-12-31', verbose_name='Дата по')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_price.item', verbose_name='Наименование')),
            ],
        ),
    ]
