# Generated by Django 3.1.2 on 2020-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_price', '0005_auto_20201025_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата по'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата с'),
        ),
    ]
